// RENDER IN APP COMPONENT
// DECIDIR SE A MENSAGEM DO BUTTON VAI SER NO SERVER SIDE OU NO CLIENT SIDE
// NAO PRECISA FAZER NOS 2 CASOS
// QUEM ESTA MANDANDO O REQUEST ´E QUEM ESTA CLICANDO NO BOTAO 
// QUANDO OS BOTOES SAO CLICADOS ELES DEVEM MUDAR O TEXTO QUE ESTA MOSTRANDO ALI 
// O ID SERA PEGO DO COOKIE EDEVE SER ARMAZENADO EM UM A ARRAY VAZIA
// 